services:
  backend:
    build:
      context: ./backend
    command: python api.py
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend/embedding_cache:/app/embedding_cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - poke-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./nginx-dev.conf:/etc/nginx/nginx-DEV.conf:ro
      - ./nginx-prod.conf:/etc/nginx/nginx-PROD.conf:ro
      - ./certbot-certs:/etc/letsencrypt
      - ./certbot-webroot:/var/www/html
    command: /bin/bash -c "envsubst '$$CORS_ORIGIN $$API_DOMAIN $$ENVIRONMENT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && envsubst '$$CORS_ORIGIN $$API_DOMAIN $$ENVIRONMENT' < /etc/nginx/nginx-$$ENVIRONMENT.conf > /etc/nginx/nginx-env.conf && nginx -g 'daemon off;'"

    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/v1/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - API_DOMAIN=${API_DOMAIN:-localhost}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:8080}
      - ENVIRONMENT=${ENVIRONMENT:-DEV}
    networks:
      - poke-network



networks:
  poke-network: