services:
  backend:
    build:
      context: ./backend
    command: python api.py
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend/embedding_cache:/app/embedding_cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - poke-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./nginx-https.conf:/etc/nginx/nginx-https.conf.template:ro
      - certbot-certs:/etc/letsencrypt
      - certbot-webroot:/var/www/html
    command: /bin/bash -c "envsubst '$$CORS_ORIGIN $$API_DOMAIN $$ENVIRONMENT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/v1/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - API_DOMAIN=${API_DOMAIN:-localhost}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:8080}
      - ENVIRONMENT=${ENVIRONMENT:-DEV}
    networks:
      - poke-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-certs:/etc/letsencrypt
      - ./certbot-init.sh:/certbot-init.sh:ro
    entrypoint: ["/bin/sh"]
    command: ["/certbot-init.sh"]
    environment:
      - API_DOMAIN=${API_DOMAIN:-localhost}
      - ENVIRONMENT=${ENVIRONMENT:-DEV}
    depends_on:
      nginx:
        condition: service_started
    networks:
      - poke-network

  certbot-renew:
    image: certbot/certbot:latest
    volumes:
      - certbot-certs:/etc/letsencrypt
      - ./certbot-renew.sh:/certbot-renew.sh:ro
    entrypoint: ["/bin/sh"]
    command: ["/certbot-renew.sh"]
    environment:
      - API_DOMAIN=${API_DOMAIN:-localhost}
      - ENVIRONMENT=${ENVIRONMENT:-DEV}
    depends_on:
      - nginx
    networks:
      - poke-network

networks:
  poke-network:
volumes:
  certbot-certs:
  certbot-webroot: