services:
  backend:
    build:
      context: ./backend
    command: python api.py
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend/embedding_cache:/app/embedding_cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - poke-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - certbot-certs:/etc/letsencrypt
    command: /bin/bash -c "envsubst '$$CORS_ORIGIN $$API_DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/v1/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - API_DOMAIN=${API_DOMAIN:-localhost}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:8080}
    networks:
      - poke-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      - API_DOMAIN=${API_DOMAIN:-localhost}
    depends_on:
      - nginx
    networks:
      - poke-network

networks:
  poke-network:
volumes:
  certbot-certs: